"""Initial schema creation

Revision ID: 97913c3b0e4d
Revises: 
Create Date: 2026-01-20 20:11:35.345783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97913c3b0e4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('control_value', sa.String(length=100), nullable=False),
    sa.Column('test_value', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('control_trades', sa.Integer(), nullable=True),
    sa.Column('test_trades', sa.Integer(), nullable=True),
    sa.Column('control_win_rate', sa.Float(), nullable=True),
    sa.Column('test_win_rate', sa.Float(), nullable=True),
    sa.Column('control_avg_roi', sa.Float(), nullable=True),
    sa.Column('test_avg_roi', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_experiment_id'), 'experiments', ['experiment_id'], unique=True)
    op.create_index(op.f('ix_experiments_parameter_name'), 'experiments', ['parameter_name'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('learning_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('pattern_name', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('parameter_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('expected_improvement', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_history_event_date'), 'learning_history', ['event_date'], unique=False)
    op.create_index(op.f('ix_learning_history_event_type'), 'learning_history', ['event_type'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_name', sa.String(length=200), nullable=False),
    sa.Column('pattern_value', sa.String(length=100), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_roi', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('date_detected', sa.DateTime(), nullable=False),
    sa.Column('date_last_validated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_pattern_type'), 'patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_patterns_status'), 'patterns', ['status'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.String(length=50), nullable=False),
    sa.Column('trade_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_premium', sa.Float(), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('current_premium', sa.Float(), nullable=True),
    sa.Column('current_pnl', sa.Float(), nullable=True),
    sa.Column('current_pnl_pct', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('approaching_stop_loss', sa.Boolean(), nullable=True),
    sa.Column('approaching_profit_target', sa.Boolean(), nullable=True),
    sa.Column('approaching_expiration', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_position_id'), 'positions', ['position_id'], unique=True)
    op.create_index(op.f('ix_positions_trade_id'), 'positions', ['trade_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_premium', sa.Float(), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('exit_premium', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_pct', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=True),
    sa.Column('otm_pct', sa.Float(), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=True),
    sa.Column('vix_at_entry', sa.Float(), nullable=True),
    sa.Column('vix_at_exit', sa.Float(), nullable=True),
    sa.Column('spy_price_at_entry', sa.Float(), nullable=True),
    sa.Column('spy_price_at_exit', sa.Float(), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('is_experiment', sa.Boolean(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_entry_date'), 'trades', ['entry_date'], unique=False)
    op.create_index(op.f('ix_trades_exit_date'), 'trades', ['exit_date'], unique=False)
    op.create_index(op.f('ix_trades_is_experiment'), 'trades', ['is_experiment'], unique=False)
    op.create_index(op.f('ix_trades_sector'), 'trades', ['sector'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_sector'), table_name='trades')
    op.drop_index(op.f('ix_trades_is_experiment'), table_name='trades')
    op.drop_index(op.f('ix_trades_exit_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_date'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_positions_trade_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_position_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_patterns_status'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_pattern_type'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_learning_history_event_type'), table_name='learning_history')
    op.drop_index(op.f('ix_learning_history_event_date'), table_name='learning_history')
    op.drop_table('learning_history')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_parameter_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_experiment_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
