"""postgresql_baseline

Revision ID: b2f71fc074b9
Revises: 
Create Date: 2026-02-11 12:25:10.202873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f71fc074b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('control_value', sa.String(length=100), nullable=False),
    sa.Column('test_value', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('control_trades', sa.Integer(), nullable=True),
    sa.Column('test_trades', sa.Integer(), nullable=True),
    sa.Column('control_win_rate', sa.Float(), nullable=True),
    sa.Column('test_win_rate', sa.Float(), nullable=True),
    sa.Column('control_avg_roi', sa.Float(), nullable=True),
    sa.Column('test_avg_roi', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_experiment_id'), 'experiments', ['experiment_id'], unique=True)
    op.create_index(op.f('ix_experiments_parameter_name'), 'experiments', ['parameter_name'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('learning_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('pattern_name', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('parameter_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('expected_improvement', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_history_event_date'), 'learning_history', ['event_date'], unique=False)
    op.create_index(op.f('ix_learning_history_event_type'), 'learning_history', ['event_type'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_name', sa.String(length=200), nullable=False),
    sa.Column('pattern_value', sa.String(length=100), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_roi', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('date_detected', sa.DateTime(), nullable=False),
    sa.Column('date_last_validated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_pattern_type'), 'patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_patterns_status'), 'patterns', ['status'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.String(length=50), nullable=False),
    sa.Column('trade_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_premium', sa.Float(), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('current_premium', sa.Float(), nullable=True),
    sa.Column('current_pnl', sa.Float(), nullable=True),
    sa.Column('current_pnl_pct', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('approaching_stop_loss', sa.Boolean(), nullable=True),
    sa.Column('approaching_profit_target', sa.Boolean(), nullable=True),
    sa.Column('approaching_expiration', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_position_id'), 'positions', ['position_id'], unique=True)
    op.create_index(op.f('ix_positions_trade_id'), 'positions', ['trade_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('config_used', sa.JSON(), nullable=True),
    sa.Column('total_candidates', sa.Integer(), nullable=True),
    sa.Column('validated_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_scan_timestamp'), 'scan_results', ['scan_timestamp'], unique=False)
    op.create_index(op.f('ix_scan_results_source'), 'scan_results', ['source'], unique=False)
    op.create_table('scan_opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('spread_pct', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('otm_pct', sa.Float(), nullable=True),
    sa.Column('dte', sa.Integer(), nullable=True),
    sa.Column('stock_price', sa.Float(), nullable=True),
    sa.Column('margin_required', sa.Float(), nullable=True),
    sa.Column('margin_efficiency', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('entry_notes', sa.Text(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('state_history', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('enrichment_snapshot', sa.JSON(), nullable=True),
    sa.Column('validation_snapshot', sa.JSON(), nullable=True),
    sa.Column('execution_snapshot', sa.JSON(), nullable=True),
    sa.Column('rejection_reasons', sa.JSON(), nullable=True),
    sa.Column('risk_check_results', sa.JSON(), nullable=True),
    sa.Column('user_decision', sa.String(length=20), nullable=True),
    sa.Column('user_decision_at', sa.DateTime(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('execution_attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('opportunity_hash', sa.String(length=64), nullable=True),
    sa.Column('staged_at', sa.DateTime(), nullable=True),
    sa.Column('staged_contracts', sa.Integer(), nullable=True),
    sa.Column('staged_limit_price', sa.Float(), nullable=True),
    sa.Column('staged_margin', sa.Float(), nullable=True),
    sa.Column('staged_margin_source', sa.String(length=20), nullable=True),
    sa.Column('portfolio_rank', sa.Integer(), nullable=True),
    sa.Column('premarket_stock_price', sa.Float(), nullable=True),
    sa.Column('premarket_deviation_pct', sa.Float(), nullable=True),
    sa.Column('premarket_checked_at', sa.DateTime(), nullable=True),
    sa.Column('premarket_new_bid', sa.Float(), nullable=True),
    sa.Column('premarket_new_ask', sa.Float(), nullable=True),
    sa.Column('adjusted_strike', sa.Float(), nullable=True),
    sa.Column('adjusted_limit_price', sa.Float(), nullable=True),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('open_stock_price', sa.Float(), nullable=True),
    sa.Column('open_deviation_pct', sa.Float(), nullable=True),
    sa.Column('open_checked_at', sa.DateTime(), nullable=True),
    sa.Column('open_bid', sa.Float(), nullable=True),
    sa.Column('open_ask', sa.Float(), nullable=True),
    sa.Column('open_limit_price', sa.Float(), nullable=True),
    sa.Column('execution_session', sa.String(length=50), nullable=True),
    sa.Column('execution_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_opportunities_executed'), 'scan_opportunities', ['executed'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_execution_session'), 'scan_opportunities', ['execution_session'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_expiration'), 'scan_opportunities', ['expiration'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_opportunity_hash'), 'scan_opportunities', ['opportunity_hash'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_portfolio_rank'), 'scan_opportunities', ['portfolio_rank'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_scan_id'), 'scan_opportunities', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_source'), 'scan_opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_staged_at'), 'scan_opportunities', ['staged_at'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_state'), 'scan_opportunities', ['state'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_symbol'), 'scan_opportunities', ['symbol'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_trade_id'), 'scan_opportunities', ['trade_id'], unique=False)
    op.create_index(op.f('ix_scan_opportunities_validation_status'), 'scan_opportunities', ['validation_status'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_premium', sa.Float(), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('exit_premium', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_pct', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=True),
    sa.Column('otm_pct', sa.Float(), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=True),
    sa.Column('vix_at_entry', sa.Float(), nullable=True),
    sa.Column('vix_at_exit', sa.Float(), nullable=True),
    sa.Column('spy_price_at_entry', sa.Float(), nullable=True),
    sa.Column('spy_price_at_exit', sa.Float(), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('is_experiment', sa.Boolean(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('tws_status', sa.String(length=50), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('fill_time', sa.DateTime(), nullable=True),
    sa.Column('fill_price_discrepancy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_entry_date'), 'trades', ['entry_date'], unique=False)
    op.create_index(op.f('ix_trades_exit_date'), 'trades', ['exit_date'], unique=False)
    op.create_index(op.f('ix_trades_is_experiment'), 'trades', ['is_experiment'], unique=False)
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_trades_sector'), 'trades', ['sector'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    op.create_table('position_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('current_premium', sa.Float(), nullable=True),
    sa.Column('current_pnl', sa.Float(), nullable=True),
    sa.Column('current_pnl_pct', sa.Float(), nullable=True),
    sa.Column('dte_remaining', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('stock_price', sa.Float(), nullable=True),
    sa.Column('distance_to_strike_pct', sa.Float(), nullable=True),
    sa.Column('vix', sa.Float(), nullable=True),
    sa.Column('spy_price', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_snapshots_dte_remaining'), 'position_snapshots', ['dte_remaining'], unique=False)
    op.create_index(op.f('ix_position_snapshots_snapshot_date'), 'position_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_position_snapshots_trade_id'), 'position_snapshots', ['trade_id'], unique=False)
    op.create_table('trade_entry_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('mid', sa.Float(), nullable=True),
    sa.Column('entry_premium', sa.Float(), nullable=False),
    sa.Column('spread_pct', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('rho', sa.Float(), nullable=True),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.Column('iv_percentile', sa.Float(), nullable=True),
    sa.Column('hv_20', sa.Float(), nullable=True),
    sa.Column('iv_hv_ratio', sa.Float(), nullable=True),
    sa.Column('option_volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('volume_oi_ratio', sa.Float(), nullable=True),
    sa.Column('stock_price', sa.Float(), nullable=False),
    sa.Column('stock_open', sa.Float(), nullable=True),
    sa.Column('stock_high', sa.Float(), nullable=True),
    sa.Column('stock_low', sa.Float(), nullable=True),
    sa.Column('stock_prev_close', sa.Float(), nullable=True),
    sa.Column('stock_change_pct', sa.Float(), nullable=True),
    sa.Column('otm_pct', sa.Float(), nullable=True),
    sa.Column('otm_dollars', sa.Float(), nullable=True),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('margin_requirement', sa.Float(), nullable=True),
    sa.Column('margin_efficiency_pct', sa.Float(), nullable=True),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('trend_strength', sa.Float(), nullable=True),
    sa.Column('price_vs_sma20_pct', sa.Float(), nullable=True),
    sa.Column('price_vs_sma50_pct', sa.Float(), nullable=True),
    sa.Column('spy_price', sa.Float(), nullable=True),
    sa.Column('spy_change_pct', sa.Float(), nullable=True),
    sa.Column('vix', sa.Float(), nullable=True),
    sa.Column('vix_change_pct', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('rsi_7', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('plus_di', sa.Float(), nullable=True),
    sa.Column('minus_di', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('bb_position', sa.Float(), nullable=True),
    sa.Column('support_1', sa.Float(), nullable=True),
    sa.Column('support_2', sa.Float(), nullable=True),
    sa.Column('resistance_1', sa.Float(), nullable=True),
    sa.Column('resistance_2', sa.Float(), nullable=True),
    sa.Column('distance_to_support_pct', sa.Float(), nullable=True),
    sa.Column('earnings_date', sa.Date(), nullable=True),
    sa.Column('days_to_earnings', sa.Integer(), nullable=True),
    sa.Column('earnings_in_dte', sa.Boolean(), nullable=True),
    sa.Column('qqq_price', sa.Float(), nullable=True),
    sa.Column('qqq_change_pct', sa.Float(), nullable=True),
    sa.Column('iwm_price', sa.Float(), nullable=True),
    sa.Column('iwm_change_pct', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('sector_etf', sa.String(length=10), nullable=True),
    sa.Column('sector_change_1d', sa.Float(), nullable=True),
    sa.Column('sector_change_5d', sa.Float(), nullable=True),
    sa.Column('vol_regime', sa.String(length=20), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_opex_week', sa.Boolean(), nullable=True),
    sa.Column('days_to_fomc', sa.Integer(), nullable=True),
    sa.Column('earnings_timing', sa.String(length=10), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['scan_opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_entry_snapshots_opportunity_id'), 'trade_entry_snapshots', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_trade_entry_snapshots_trade_id'), 'trade_entry_snapshots', ['trade_id'], unique=False)
    op.create_table('trade_exit_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('exit_date', sa.DateTime(), nullable=False),
    sa.Column('exit_premium', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(length=50), nullable=False),
    sa.Column('days_held', sa.Integer(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('roi_pct', sa.Float(), nullable=True),
    sa.Column('roi_on_margin', sa.Float(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('max_profit_captured_pct', sa.Float(), nullable=True),
    sa.Column('exit_iv', sa.Float(), nullable=True),
    sa.Column('iv_change_during_trade', sa.Float(), nullable=True),
    sa.Column('stock_price_at_exit', sa.Float(), nullable=True),
    sa.Column('stock_change_during_trade_pct', sa.Float(), nullable=True),
    sa.Column('vix_at_exit', sa.Float(), nullable=True),
    sa.Column('vix_change_during_trade', sa.Float(), nullable=True),
    sa.Column('closest_to_strike_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('max_profit_pct', sa.Float(), nullable=True),
    sa.Column('trade_quality_score', sa.Float(), nullable=True),
    sa.Column('risk_adjusted_return', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_exit_snapshots_exit_date'), 'trade_exit_snapshots', ['exit_date'], unique=False)
    op.create_index(op.f('ix_trade_exit_snapshots_exit_reason'), 'trade_exit_snapshots', ['exit_reason'], unique=False)
    op.create_index(op.f('ix_trade_exit_snapshots_trade_id'), 'trade_exit_snapshots', ['trade_id'], unique=True)
    op.create_index(op.f('ix_trade_exit_snapshots_win'), 'trade_exit_snapshots', ['win'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_exit_snapshots_win'), table_name='trade_exit_snapshots')
    op.drop_index(op.f('ix_trade_exit_snapshots_trade_id'), table_name='trade_exit_snapshots')
    op.drop_index(op.f('ix_trade_exit_snapshots_exit_reason'), table_name='trade_exit_snapshots')
    op.drop_index(op.f('ix_trade_exit_snapshots_exit_date'), table_name='trade_exit_snapshots')
    op.drop_table('trade_exit_snapshots')
    op.drop_index(op.f('ix_trade_entry_snapshots_trade_id'), table_name='trade_entry_snapshots')
    op.drop_index(op.f('ix_trade_entry_snapshots_opportunity_id'), table_name='trade_entry_snapshots')
    op.drop_table('trade_entry_snapshots')
    op.drop_index(op.f('ix_position_snapshots_trade_id'), table_name='position_snapshots')
    op.drop_index(op.f('ix_position_snapshots_snapshot_date'), table_name='position_snapshots')
    op.drop_index(op.f('ix_position_snapshots_dte_remaining'), table_name='position_snapshots')
    op.drop_table('position_snapshots')
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_sector'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_is_experiment'), table_name='trades')
    op.drop_index(op.f('ix_trades_exit_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_date'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_scan_opportunities_validation_status'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_trade_id'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_symbol'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_state'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_staged_at'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_source'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_scan_id'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_portfolio_rank'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_opportunity_hash'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_expiration'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_execution_session'), table_name='scan_opportunities')
    op.drop_index(op.f('ix_scan_opportunities_executed'), table_name='scan_opportunities')
    op.drop_table('scan_opportunities')
    op.drop_index(op.f('ix_scan_results_source'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_scan_timestamp'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_positions_trade_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_position_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_patterns_status'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_pattern_type'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_learning_history_event_type'), table_name='learning_history')
    op.drop_index(op.f('ix_learning_history_event_date'), table_name='learning_history')
    op.drop_table('learning_history')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_parameter_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_experiment_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
