#!/bin/bash
# Auto-generated by: nakedtrader daemon install-service --dashboard
# Waits for TAAD daemon to be ready, then starts the dashboard.

PID_FILE="/Users/axel/projects/trading/trading_agent/run/taad.pid"
MAX_WAIT=120  # seconds
WAITED=0

echo "$(date): Waiting for TAAD daemon (PID file: $PID_FILE)..."

while [ ! -f "$PID_FILE" ] && [ $WAITED -lt $MAX_WAIT ]; do
    sleep 5
    WAITED=$((WAITED + 5))
done

if [ -f "$PID_FILE" ]; then
    DAEMON_PID=$(cat "$PID_FILE")
    echo "$(date): Daemon running (pid=$DAEMON_PID). Starting dashboard..."
else
    echo "$(date): WARNING - Daemon PID file not found after ${MAX_WAIT}s. Starting dashboard anyway."
fi

cd "/Users/axel/projects/trading/trading_agent"
exec "/Users/axel/projects/trading/trading_agent/venv/bin/python3.11" -m src.cli.main dashboard
